export { default as Button } from "./Button"; 
export { default as Disc } from "./Disc"; 
export { default as Header } from "./Header";
export { default as Heading } from "./Heading";
export { default as Footer } from "./Footer";
export { default as Game } from "./Game";
export { default as Logo } from "./Logo";
export { default as ScoreCard } from "./ScoreCard";
export { default as ScoreCardEmoji } from "./ScoreCardEmoji"; 
